### ISSUE TITLE
下载任务如何手动从下载中变为等待中

### ISSUE THREAD

**Issue by EricInCD** [wyouflf/xUtils#134]
项目需求是，只有一个下载中的任务
点击其中一个等待中的任务，此任务变为下载中的任务，之前下载中的任务变为等待中。
请教实现方法。谢谢！

**Comment by linwoain** [comment]
download方法有个HttpHandler的返回值，使用它的cancel方法即可停止一个下载

**Comment by EricInCD** [comment]
感谢楼上的回答。但是cancel方法只是把一个任务从下载中变为暂停状态，如何能变成等待中的状态呢？

**Comment by linwoain** [comment]
后台暂停，前台显示等待中不就可以了

**Comment by alafighting** [comment]
那不行，暂停就是取消了；等待，只是在排队。
这应该需要自己维护。xUtils的stop()好像不能用。
你通过download()、cancel()控制下载、取消。自己增强实现等待。

**Comment by EricInCD** [comment]
嗯，我试试。多谢各位指点

**Comment by EricInCD** [comment]
已解决，任务1为进行中的任务，任务2为等待中的任务
点击任务2时：
1、先暂停任务1，此时任务2会自动开始
2、在任务2回调的START状态中，将任务1继续，此时由于任务2已经开始了，任务1就只能等待了
需求的目标达成
