### ISSUE TITLE
Nexus 5 with android 5.0 的BitmapUtils问题

### ISSUE THREAD

**Issue by llitfkitfk** [wyouflf/xUtils#138]
Log info:
![](https://cloud.githubusercontent.com/assets/2404785/5916464/7ebb3792-a64c-11e4-8dc9-8be6f276e8f3.png)

Issue Location:
![](https://cloud.githubusercontent.com/assets/2404785/5916484/c120ddc6-a64c-11e4-9821-e9fad6d1ed55.png)

**Comment by alafighting** [comment]
更换为最新版的jar

**Comment by llitfkitfk** [comment]
感谢..

PS: 我才不会告诉你从头debug了一下午才找到的。
