### ISSUE TITLE
HttpUtils 可否增加 快速提交对象

### ISSUE THREAD

**Issue by TuWei1992** [wyouflf/xUtils#139]
可否增加类似 json 的 序列化方法, 将一个对象序列化为表单键值对, 然后提交? 还是现在有类似的方法?

**Comment by TuWei1992** [comment]
能不能行给个回复啊

**Comment by alafighting** [comment]
fastjson可以将实体类序列化为json，也可以将json解析成实体类。

**Comment by TuWei1992** [comment]
我知道,我的意思是将某个bean 转为 attr1=xx&attr2=xx ..... 这种 而不是 obj={attr1:xx,attr2:xx}

**Comment by alafighting** [comment]
将实体类序列化提交表单，不能提高效率，反而局限性太大。
自己为每个实体类增加一个方法，手动实现转化，更灵活。

**Comment by TuWei1992** [comment]
.... 这种方法应该加到框架中, 对于简单而字段较多的bean 这种方法可以做到快速提交,

**Comment by TuWei1992** [comment]
像是 jQuery, 对于ajax提交 就提供了 - serialize() 方法

**Comment by alafighting** [comment]
一般表单能有多复杂？大部分都比较简单。
如果自动序列化，关于key则无法很好控制，通过注解的方式，反射又降低了性能。
jQuery那是针对from表单。只是将表单要提交的值，序列化。这是from本身的功能。

**Comment by TuWei1992** [comment]
你要是一个bean有二十个字段,你还得一个个addQueryStringParam 吗

**Comment by alafighting** [comment]
代码只需要写一次，花费时间很少，提高的性能却是永久性的。

**Comment by TuWei1992** [comment]
关于key, 通用的做法就是将字段名作为key

**Comment by TuWei1992** [comment]
我严重不同意你这种想法, 讲一个bean 序列化能浪费多少性能,作为框架 ,最重要的作用就是write less do more

**Comment by alafighting** [comment]
我严重不同意你这种想法, 讲一个bean 序列化能写多少代码？
作为开发人员，不知道，IDE可以帮你自动生成。
