### ISSUE TITLE
ViewUtils.inject(this);报错

### ISSUE THREAD

**Issue by qinxianyuzou** [wyouflf/xUtils#152]
不知道为什么同样配置的activity，一些可以初始化正常使用，这个却不行，代码都是复制过来的，第72行报错就是ViewUtils.inject(this);这句。跪求解决办法
错误日志
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): invalid value for field
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): java.lang.IllegalArgumentException: invalid value for field
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at java.lang.reflect.Field.setField(Native Method)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at java.lang.reflect.Field.set(Field.java:585)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at com.lidroid.xutils.ViewUtils.injectObject(ViewUtils.java:98)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at com.lidroid.xutils.ViewUtils.inject(ViewUtils.java:49)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at com.againvip.zailai.activity.wallet.Wallet_Activity.onCreate(Wallet_Activity.java:72)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.Activity.performCreate(Activity.java:5246)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.ActivityThread.access$800(ActivityThread.java:138)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.os.Looper.loop(Looper.java:136)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
03-13 15:36:22.993: E/ViewUtils.injectObject(L:101)(12461): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mayqlzu** [comment]
我也遇到了这个问题，lib的版本号是2.6.14；
你为何关闭了这个bug呢？是修好了吗？

**Comment by mayqlzu** [comment]
问题找到了，原来是layout里申明的控件类型和java代码里申明的类型不一致导致的；

**Comment by SheepYoung** [comment]
我使用源码自己改了，这玩意组好就是作者改一下，实在不行就直接用源码，不用jar，我还发现了一个线程使用的问题，会导致memry cache失效的，也一起改了。 估计这玩意可能已经已经停止更新了， 3.x完全兼容2.x，不知道作者为什么这么做。用了2.x 不想动了，怕有影响。

________________________________
发件人: mayqlzu <notifications@github.com>
发送时间: 2016年6月15日 17:34
收件人: wyouflf/xUtils
主题: Re: [wyouflf/xUtils] ViewUtils.inject(this);报错 (#152)


我也遇到了这个问题，lib的版本号是2.6.14；
你为何关闭了这个bug呢？是修好了吗？

―

**Comment by MirShu** [comment]
studio 加上
 compile 'org.xutils:xutils:3.5.0'
 compile 'com.jiechic.library:xUtils:2.6.14'
这两句 搞定
