### ISSUE TITLE
发现了一个bug，当布局文件上面有include布局的时候就不能初始化

### ISSUE THREAD

**Issue by qinxianyuzou** [wyouflf/xUtils#154]
经过复杂的对比发现，当布局文件里面使用了include布局ViewUtils.inject(this);就会初始化错误，跪求解决

**Comment by xiaoyangzi** [comment]
真的！

**Comment by qinxianyuzou** [comment]
经过研究发现，并不是框架有问题，而是我初始化的控件类型错了，但是提示得并不准确，导致一直不能找到问题所在
