### ISSUE TITLE
怎么POST一个Json格式的Body呢?

### ISSUE THREAD

**Issue by heramerom** [wyouflf/xUtils#173]
有些Body是Form 格式的，有些是Json格式的，甚至有些是自建格式的。怎么才能支持这些格式呢？

**Comment by rexcheung** [comment]
今天刚好遇到这个需求， 在Google上面就搜到这里来了，下面的方法可以用，已经试过
http://www.cnblogs.com/madyina/p/4300090.html

**Comment by heramerom** [comment]
谢谢
