### ISSUE TITLE
sendSync  ： retry error, curr request is null

### ISSUE THREAD

**Issue by nickzhanglv** [wyouflf/xUtils#205]
HttpUtils http = new HttpUtils();
        try {
            ResponseStream response = http.sendSync(HttpRequest.HttpMethod.POST,
                    Constants.URI_LOGIN,
                    params);
            String str = response.readString();
            Log.d(TAG, str);
        } catch (HttpException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

报错  retry error, curr request is null 
请问如何使用 sendSync

**Comment by Sogrey** [comment]
设置初始化试试：
// 设置请求超时时间为5秒
		HttpUtils	mHttp = new HttpUtils(1000 * 5);
		mHttp.configSoTimeout(1000 * 5);
		mHttp.configRequestRetryCount(4);
		mHttp.configResponseTextCharset("UTF-8");
		mHttp.configHttpCacheSize(0);
		// 设置线程池线程数上限
		mHttp.configRequestThreadPoolSize(MAX_THREAD_NUM);

**Comment by nickzhanglv** [comment]
Thanks you !
